- force-app/main/default/objects/pse__Proj__c/fields/CT_Acquisition__c.field-meta.xml
> [DevOps Center] Merge WI-000825 to Integration

- force-app/main/default/flexipages/Corporate_Opp_Record_Page.flexipage-meta.xml
- force-app/main/default/flexipages/Opportunity_Record_Page.flexipage-meta.xml
> [DevOps Center] Merge WI-000835 to Integration

- force-app/main/default/flexipages/Account_Record_Page.flexipage-meta.xml
> [DevOps Center] Merge WI-000841 to Integration

- force-app/main/default/objects/Opportunity/validationRules/V2_Opp_Stage_Flirt.validationRule-meta.xml
> [DevOps Center] Merge WI-000842 to Integration

- force-app/main/default/flexipages/Account_Record_Page.flexipage-meta.xml
- force-app/main/default/objects/Opportunity/validationRules/V2_Opp_Stage_Flirt.validationRule-meta.xml
DevOps Center created this change request for DevOps Center use only. Due to the potential for data corruption, DO NOT MERGE this change request.
> [DO NOT MERGE] For DevOps Center use only - Integration to UAT

- force-app/main/default/objects/Case/fields/Account_Details_Completed__c.field-meta.xml
- force-app/main/default/objects/Case/fields/Account_Team_Verified__c.field-meta.xml
- force-app/main/default/objects/Case/fields/Compliance_Approval_Completed__c.field-meta.xml
- force-app/main/default/objects/Case/fields/Engagement_Doc_Submitted_for_Approver__c.field-meta.xml
- force-app/main/default/objects/Case/fields/Engagement_Document_Drafted__c.field-meta.xml
- force-app/main/default/objects/Case/fields/Engagement_Document_Sent_to_Client__c.field-meta.xml
- force-app/main/default/objects/Case/fields/Escalated_to_Risk_Team__c.field-meta.xml
- force-app/main/default/objects/Case/fields/Flags_Reviewed_and_Addressed__c.field-meta.xml
- force-app/main/default/objects/Case/fields/Form_Approval_Triggered__c.field-meta.xml
- force-app/main/default/objects/Case/fields/Onboarding_Case_Verified__c.field-meta.xml
- force-app/main/default/objects/Case/fields/Onboarding_Successful__c.field-meta.xml
- force-app/main/default/objects/Case/fields/Onboarding_Unsuccessful__c.field-meta.xml
- force-app/main/default/objects/Case/fields/Partner_Approval_Sent__c.field-meta.xml
- force-app/main/default/objects/Case/fields/Professional_Clearance_Letter_Sent__c.field-meta.xml
- force-app/main/default/objects/Case/fields/Required_Forms_Completed__c.field-meta.xml
- force-app/main/default/objects/Case/fields/Smart_Search_Checks_Performed__c.field-meta.xml
- force-app/main/default/objects/Case/fields/Smart_Search_Results_Reviewed__c.field-meta.xml
> [DevOps Center] Merge WI-000848 to Integration

- force-app/main/default/objects/Case/fields/Account_Details_Completed__c.field-meta.xml
- force-app/main/default/objects/Case/fields/Account_Team_Verified__c.field-meta.xml
- force-app/main/default/objects/Case/fields/Compliance_Approval_Completed__c.field-meta.xml
- force-app/main/default/objects/Case/fields/Engagement_Doc_Submitted_for_Approver__c.field-meta.xml
- force-app/main/default/objects/Case/fields/Engagement_Document_Drafted__c.field-meta.xml
- force-app/main/default/objects/Case/fields/Engagement_Document_Sent_to_Client__c.field-meta.xml
- force-app/main/default/objects/Case/fields/Escalated_to_Risk_Team__c.field-meta.xml
- force-app/main/default/objects/Case/fields/Flags_Reviewed_and_Addressed__c.field-meta.xml
- force-app/main/default/objects/Case/fields/Form_Approval_Triggered__c.field-meta.xml
- force-app/main/default/objects/Case/fields/Onboarding_Case_Verified__c.field-meta.xml
- force-app/main/default/objects/Case/fields/Partner_Approval_Sent__c.field-meta.xml
- force-app/main/default/objects/Case/fields/Professional_Clearance_Letter_Sent__c.field-meta.xml
- force-app/main/default/objects/Case/fields/Required_Forms_Completed__c.field-meta.xml
- force-app/main/default/objects/Case/fields/Smart_Search_Checks_Performed__c.field-meta.xml
- force-app/main/default/objects/Case/fields/Smart_Search_Results_Reviewed__c.field-meta.xml
> [DevOps Center] Merge WI-000851 to Integration

- force-app/main/default/objects/Case/fields/Case_Team_Updated__c.field-meta.xml
- force-app/main/default/objects/Case/fields/LC_Assigned_to_Case__c.field-meta.xml
> [DevOps Center] Merge WI-000854 to Integration

- force-app/main/default/pathAssistants/Case_Adhoc_Check.pathAssistant-meta.xml
- force-app/main/default/pathAssistants/Case_Onboarding_Path.pathAssistant-meta.xml
- force-app/main/default/pathAssistants/Case_Service_Line.pathAssistant-meta.xml
- force-app/main/default/pathAssistants/Case_Yearly_Check.pathAssistant-meta.xml
> [DevOps Center] Merge WI-000853 to Integration

- force-app/main/default/flexipages/Person_Account_Record_Page.flexipage-meta.xml
> [DevOps Center] Merge WI-000860 to Integration

- force-app/main/default/flexipages/Person_Account_Record_Page.flexipage-meta.xml
> [DevOps Center] Merge WI-000861 to Integration

- force-app/main/default/objects/SurveyInvitation/SurveyInvitation.object-meta.xml
- force-app/main/default/objects/SurveyInvitation/fields/Contact_Owner__c.field-meta.xml
> [DevOps Center] Merge WI-000866 to Integration

- force-app/main/default/flows/CT_Set_Estimate_Defaults.flow-meta.xml
- force-app/main/default/flows/Expense_without_assignment.flow-meta.xml
> [DevOps Center] Merge WI-000864 to Integration

- force-app/main/default/layouts/CP_Note__c-CP Note Layout.layout-meta.xml
- force-app/main/default/objects/CP_Note__c/fields/annotationid__c.field-meta.xml
- force-app/main/default/objects/CP_Note__c/fields/createdon__c.field-meta.xml
- force-app/main/default/objects/CP_Note__c/fields/isdocument__c.field-meta.xml
- force-app/main/default/objects/CP_Note__c/fields/notetext__c.field-meta.xml
- force-app/main/default/objects/CP_Note__c/fields/objectid__c.field-meta.xml
- force-app/main/default/objects/CP_Note__c/fields/objecttypecode__c.field-meta.xml
- force-app/main/default/objects/CP_Note__c/fields/ownerid__c.field-meta.xml
> [DevOps Center] Merge WI-000869 to Integration

- force-app/main/default/layouts/CP_Note__c-CP Note Layout.layout-meta.xml
- force-app/main/default/objects/CP_Note__c/fields/annotationid__c.field-meta.xml
- force-app/main/default/objects/CP_Note__c/fields/createdon__c.field-meta.xml
- force-app/main/default/objects/CP_Note__c/fields/isdocument__c.field-meta.xml
- force-app/main/default/objects/CP_Note__c/fields/notetext__c.field-meta.xml
- force-app/main/default/objects/CP_Note__c/fields/objectid__c.field-meta.xml
- force-app/main/default/objects/CP_Note__c/fields/objecttypecode__c.field-meta.xml
- force-app/main/default/objects/CP_Note__c/fields/ownerid__c.field-meta.xml
> [DevOps Center] Merge WI-000869 to UAT

- force-app/main/default/layouts/CP_Note__c-CP Note Layout.layout-meta.xml
- force-app/main/default/objects/CP_Note__c/fields/External_Account_ID__c.field-meta.xml
> [DevOps Center] Merge WI-000870 to Integration

- force-app/main/default/layouts/CP_Note__c-CP Note Layout.layout-meta.xml
- force-app/main/default/objects/CP_Note__c/fields/External_Account_ID__c.field-meta.xml
> [DevOps Center] Merge WI-000870 to UAT

- force-app/main/default/externalCredentials/BHAuth.externalCredential-meta.xml
- force-app/main/default/namedCredentials/BeauhurstAPI.namedCredential-meta.xml
> [DevOps Center] Merge WI-000874 to Integration

- force-app/main/default/objects/Case/validationRules/V1_OnboardingCaseClosed.validationRule-meta.xml
- force-app/main/default/quickActions/Account.LC_Update.quickAction-meta.xml
> [DevOps Center] Merge WI-000876 to Integration

- force-app/main/default/objects/Account/fields/Source__c.field-meta.xml
> [DevOps Center] Merge WI-000877 to Integration

- force-app/main/default/flows/Account_Lock_Inactive_Account.flow-meta.xml
> [DevOps Center] Merge WI-000880 to Integration

- force-app/main/default/objects/Account/fields/Source__c.field-meta.xml
> [DevOps Center] Merge WI-000877 to UAT

- force-app/main/default/customindex/Account.CP_External_ID__c.indx-meta.xml
- force-app/main/default/objects/Account/fields/CP_External_ID__c.field-meta.xml
> [DevOps Center] Merge WI-000882 to Integration

- force-app/main/default/globalValueSets/Service_Lines.globalValueSet-meta.xml
> [DevOps Center] Merge WI-000889 to Integration

- force-app/main/default/objects/ffpsai__ExpenseTypeGLAMapping__c/ffpsai__ExpenseTypeGLAMapping__c.object-meta.xml
- force-app/main/default/objects/ffpsai__ExpenseTypeGLAMapping__c/fields/ffpsai__ExpenseType__c.field-meta.xml
- force-app/main/default/objects/ffscpq__Estimated_Expense__c/ffscpq__Estimated_Expense__c.object-meta.xml
- force-app/main/default/objects/ffscpq__Estimated_Expense__c/fields/ffscpq__Type__c.field-meta.xml
- force-app/main/default/objects/pse__Expense_Limit_Rate__c/fields/pse__Type__c.field-meta.xml
- force-app/main/default/objects/pse__Expense_Limit_Rate__c/pse__Expense_Limit_Rate__c.object-meta.xml
- force-app/main/default/objects/pse__Expense__c/fieldSets/CT_Expense_Info.fieldSet-meta.xml
- force-app/main/default/objects/pse__Expense__c/fields/pse__Type__c.field-meta.xml
- force-app/main/default/objects/pse__Expense__c/pse__Expense__c.object-meta.xml
> [DevOps Center] Merge WI-000892 to Integration

- force-app/main/default/objects/Contact/fields/BuyerAttributes.field-meta.xml
> [DevOps Center] Merge WI-000895 to Integration

- force-app/main/default/classes/SmartSearchCompCont.cls
- force-app/main/default/classes/SmartSearchCompCont.cls-meta.xml
> [DevOps Center] Merge WI-000898 to Integration

- force-app/main/default/objects/pse__Assignment__c/fields/Work_Activity__c.field-meta.xml
- force-app/main/default/objects/pse__Assignment__c/pse__Assignment__c.object-meta.xml
- force-app/main/default/reportTypes/Project_Assignment_and_Timecard.reportType-meta.xml
> [DevOps Center] Merge WI-000899 to UAT

- force-app/main/default/flows/Opportunity_Update_Naming_Convention.flow-meta.xml
> [DevOps Center] Merge WI-000902 to Integration

- force-app/main/default/flows/Opportunity_Update_Naming_Convention.flow-meta.xml
> [DevOps Center] Merge WI-000902 to UAT

- force-app/main/default/objects/pse__Milestone__c/listViews/psaws__Late_For_My_Projects.listView-meta.xml
- force-app/main/default/objects/pse__Proj__c/listViews/My_project_65_recovery.listView-meta.xml
> [DevOps Center] Merge WI-000904 to Integration

- force-app/main/default/customindex/pse__Resource_Request__c.External_ID__c.indx-meta.xml
- force-app/main/default/objects/pse__Resource_Request__c/fields/External_ID__c.field-meta.xml
- force-app/main/default/objects/pse__Resource_Request__c/pse__Resource_Request__c.object-meta.xml
> [DevOps Center] Merge WI-000907 to Integration

- force-app/main/default/customindex/pse__Resource_Request__c.External_ID__c.indx-meta.xml
- force-app/main/default/objects/pse__Resource_Request__c/fields/External_ID__c.field-meta.xml
- force-app/main/default/objects/pse__Resource_Request__c/pse__Resource_Request__c.object-meta.xml
> [DevOps Center] Merge WI-000907 to UAT

- force-app/main/default/permissionsets/Confidential_Notes_Access.permissionset-meta.xml
> [DevOps Center] Merge WI-000912 to Integration

- force-app/main/default/layouts/CP_Note__c-CP Note Layout.layout-meta.xml
- force-app/main/default/objects/CP_Note__c/fields/Contact__c.field-meta.xml
- force-app/main/default/objects/CP_Note__c/fields/Opportunity__c.field-meta.xml
> [DevOps Center] Merge WI-000919 to Integration

- force-app/main/default/layouts/CP_Note__c-CP Note Layout.layout-meta.xml
- force-app/main/default/objects/CP_Note__c/fields/Contact__c.field-meta.xml
- force-app/main/default/objects/CP_Note__c/fields/Opportunity__c.field-meta.xml
> [DevOps Center] Merge WI-000919 to UAT

- force-app/main/default/permissionsets/Confidential_Notes_Access.permissionset-meta.xml
> [DevOps Center] Merge WI-000912 to UAT

- force-app/main/default/flows/Account_Inactive_Validation.flow-meta.xml
> [DevOps Center] Merge WI-000922 to Integration

- force-app/main/default/objects/pse__Expense__c/fields/CT_Expense_VAT_Rate__c.field-meta.xml
> [DevOps Center] Merge WI-000923 to Integration

- force-app/main/default/objects/pse__Expense__c/fields/CT_Expense_VAT_Rate__c.field-meta.xml
> [DevOps Center] Merge WI-000923 to UAT

- force-app/main/default/objects/Opportunity/validationRules/V2_Opp_Stage_Flirt.validationRule-meta.xml
> [DevOps Center] Merge WI-000925 to Integration

- force-app/main/default/flexipages/Audit_Register_Record_Page.flexipage-meta.xml
- force-app/main/default/flows/Audit_Register_On_Create.flow-meta.xml
- force-app/main/default/objects/Audit_Register__c/fields/CP_Practice__c.field-meta.xml
> [DevOps Center] Merge WI-000927 to Integration

- force-app/main/default/objects/Opportunity/validationRules/V2_Opp_Stage_Flirt.validationRule-meta.xml
> [DevOps Center] Merge WI-000925 to UAT

- force-app/main/default/flexipages/Audit_Register_Record_Page.flexipage-meta.xml
- force-app/main/default/flows/Audit_Register_On_Create.flow-meta.xml
- force-app/main/default/objects/Audit_Register__c/fields/CP_Practice__c.field-meta.xml
> [DevOps Center] Merge WI-000927 to UAT

- force-app/main/default/dashboards/HomePageDashboardsFolder/gRJGvTAAmukqGHIWcTOGzbOgMErUxp.dashboard-meta.xml
- force-app/main/default/dashboards/HomePageDashboardsFolder/yVGjJkaUxaYtqnbPEbChPDTSJcAKtX.dashboard-meta.xml
> [DevOps Center] Merge WI-000929 to Integration

- force-app/main/default/flows/Opportunity_Send_Custom_Notification.flow-meta.xml
> [DevOps Center] Merge WI-000932 to Integration

- force-app/main/default/objects/Activity/Activity.object-meta.xml
- force-app/main/default/objects/Activity/fields/Meeting_Subtype__c.field-meta.xml
> [DevOps Center] Merge WI-000933 to Integration

- force-app/main/default/approvalProcesses/Case.CAF_Form_Approval.approvalProcess-meta.xml
- force-app/main/default/approvalProcesses/Case.Engagement_Pack_Approval.approvalProcess-meta.xml
- force-app/main/default/approvalProcesses/Case.Escalate_Case.approvalProcess-meta.xml
- force-app/main/default/approvalProcesses/Case.PEP_SIP_RCA_Approval.approvalProcess-meta.xml
- force-app/main/default/approvalProcesses/Case.Partner_Approval.approvalProcess-meta.xml
- force-app/main/default/approvalProcesses/Case.Risk_Compliance_Approval.approvalProcess-meta.xml
- force-app/main/default/approvalProcesses/Opportunity.BTC_THG_PCC_Estimate_Approval.approvalProcess-meta.xml
- force-app/main/default/approvalProcesses/Opportunity.Law_Estimate_Approval.approvalProcess-meta.xml
- force-app/main/default/approvalProcesses/Opportunity.Opportunity_Audit_Client_Approval.approvalProcess-meta.xml
- force-app/main/default/approvalProcesses/Opportunity.THG_Audit_Partner_Approval.approvalProcess-meta.xml
> [DevOps Center] Merge WI-000935 to Integration

- force-app/main/default/objects/pse__Milestone__c/fields/Project_Partner_is_Current_User__c.field-meta.xml
- force-app/main/default/objects/pse__Proj__c/fields/Project_Partner_is_Current_User__c.field-meta.xml
- force-app/main/default/permissionsets/Cooper_Parry_PSA_Permission_Set.permissionset-meta.xml
- force-app/main/default/permissionsets/Cooper_Parry_PSA_Permission_Set_for_Project_Managers.permissionset-meta.xml
- force-app/main/default/permissionsets/Cooper_Parry_User_Fields.permissionset-meta.xml
> [DevOps Center] Merge WI-000938 to Integration

- force-app/main/default/layouts/Case-Case Layout.layout-meta.xml
> [DevOps Center] Merge WI-000939 to Integration

- force-app/main/default/layouts/Audit_Register__c-Audit Register Layout.layout-meta.xml
- force-app/main/default/objects/Audit_Register__c/Audit_Register__c.object-meta.xml
> [DevOps Center] Merge WI-000921 to Integration

- force-app/main/default/flexipages/ProjectLightningPage1.flexipage-meta.xml
- force-app/main/default/objects/pse__Assignment__c/fieldSets/CT_Assignment_Extra_Fields.fieldSet-meta.xml
- force-app/main/default/objects/pse__Assignment__c/validationRules/Milestone_Required.validationRule-meta.xml
- force-app/main/default/objects/pse__Milestone__c/validationRules/Description_needed_for_Billing.validationRule-meta.xml
- force-app/main/default/quickActions/pse__Proj__c.Roll_Forward_OLD_DO_NOT_USE.quickAction-meta.xml
> [DevOps Center] Merge WI-000945 to Integration

- force-app/main/default/flexipages/ProjectLightningPage1.flexipage-meta.xml
- force-app/main/default/objects/pse__Assignment__c/fieldSets/CT_Assignment_Extra_Fields.fieldSet-meta.xml
- force-app/main/default/objects/pse__Assignment__c/validationRules/Milestone_Required.validationRule-meta.xml
- force-app/main/default/objects/pse__Milestone__c/validationRules/Description_needed_for_Billing.validationRule-meta.xml
- force-app/main/default/quickActions/pse__Proj__c.Roll_Forward_OLD_DO_NOT_USE.quickAction-meta.xml
> [DevOps Center] Merge WI-000945 to UAT

- force-app/main/default/flexipages/Account_Record_Page.flexipage-meta.xml
> [DevOps Center] Merge WI-000947 to Integration

- force-app/main/default/flexipages/Account_Record_Page.flexipage-meta.xml
> [DevOps Center] Merge WI-000947 to UAT

- force-app/main/default/classes/BatchCreateSharepointFolderAccount.cls
- force-app/main/default/classes/BatchCreateSharepointFolderAccount.cls-meta.xml
- force-app/main/default/classes/BatchCreateSharepointFolderCase.cls
- force-app/main/default/classes/BatchCreateSharepointFolderCase.cls-meta.xml
- force-app/main/default/classes/CompaniesHouseController.cls
- force-app/main/default/classes/CompaniesHouseController.cls-meta.xml
- force-app/main/default/classes/SharepointAPIUtility.cls
- force-app/main/default/classes/SharepointAPIUtility.cls-meta.xml
- force-app/main/default/classes/SharepointCompCont.cls
- force-app/main/default/classes/SharepointCompCont.cls-meta.xml
- force-app/main/default/classes/SharepointCompContTest.cls
- force-app/main/default/classes/SharepointCompContTest.cls-meta.xml
- force-app/main/default/classes/SharepointUploadFileInvocable.cls
- force-app/main/default/classes/SharepointUploadFileInvocable.cls-meta.xml
- force-app/main/default/classes/SharepointUploadFileInvocableTest.cls
- force-app/main/default/classes/SharepointUploadFileInvocableTest.cls-meta.xml
- force-app/main/default/lwc/sharepointComp/sharepointComp.html
- force-app/main/default/lwc/sharepointComp/sharepointComp.js
- force-app/main/default/lwc/sharepointComp/sharepointComp.js-meta.xml
- force-app/main/default/objects/Sharepoint_Setting__c/Sharepoint_Setting__c.object-meta.xml
- force-app/main/default/objects/Sharepoint_Setting__c/fields/drive_id_secure__c.field-meta.xml
> [DevOps Center] Merge WI-000948 to Integration

- force-app/main/default/classes/BatchCreateSharepointFolderAccount.cls
- force-app/main/default/classes/BatchCreateSharepointFolderAccount.cls-meta.xml
- force-app/main/default/classes/BatchCreateSharepointFolderCase.cls
- force-app/main/default/classes/BatchCreateSharepointFolderCase.cls-meta.xml
- force-app/main/default/classes/CompaniesHouseController.cls
- force-app/main/default/classes/CompaniesHouseController.cls-meta.xml
- force-app/main/default/classes/SharepointAPIUtility.cls
- force-app/main/default/classes/SharepointAPIUtility.cls-meta.xml
- force-app/main/default/classes/SharepointCompCont.cls
- force-app/main/default/classes/SharepointCompCont.cls-meta.xml
- force-app/main/default/classes/SharepointCompContTest.cls
- force-app/main/default/classes/SharepointCompContTest.cls-meta.xml
- force-app/main/default/classes/SharepointUploadFileInvocable.cls
- force-app/main/default/classes/SharepointUploadFileInvocable.cls-meta.xml
- force-app/main/default/classes/SharepointUploadFileInvocableTest.cls
- force-app/main/default/classes/SharepointUploadFileInvocableTest.cls-meta.xml
- force-app/main/default/lwc/sharepointComp/sharepointComp.html
- force-app/main/default/lwc/sharepointComp/sharepointComp.js
- force-app/main/default/lwc/sharepointComp/sharepointComp.js-meta.xml
- force-app/main/default/objects/Sharepoint_Setting__c/Sharepoint_Setting__c.object-meta.xml
- force-app/main/default/objects/Sharepoint_Setting__c/fields/drive_id_secure__c.field-meta.xml
> [DevOps Center] Merge WI-000948 to UAT

- force-app/main/default/classes/BatchCreateSharepointFolderAccount.cls
- force-app/main/default/classes/BatchCreateSharepointFolderAccount.cls-meta.xml
- force-app/main/default/classes/BatchCreateSharepointFolderCase.cls
- force-app/main/default/classes/BatchCreateSharepointFolderCase.cls-meta.xml
- force-app/main/default/classes/CompaniesHouseController.cls
- force-app/main/default/classes/CompaniesHouseController.cls-meta.xml
- force-app/main/default/classes/SharepointAPIUtility.cls
- force-app/main/default/classes/SharepointAPIUtility.cls-meta.xml
- force-app/main/default/classes/SharepointCompCont.cls
- force-app/main/default/classes/SharepointCompCont.cls-meta.xml
- force-app/main/default/classes/SharepointCompContTest.cls
- force-app/main/default/classes/SharepointCompContTest.cls-meta.xml
- force-app/main/default/classes/SharepointUploadFileInvocable.cls
- force-app/main/default/classes/SharepointUploadFileInvocable.cls-meta.xml
- force-app/main/default/classes/SharepointUploadFileInvocableTest.cls
- force-app/main/default/classes/SharepointUploadFileInvocableTest.cls-meta.xml
- force-app/main/default/flexipages/Account_Record_Page.flexipage-meta.xml
- force-app/main/default/lwc/sharepointComp/sharepointComp.html
- force-app/main/default/lwc/sharepointComp/sharepointComp.js
- force-app/main/default/lwc/sharepointComp/sharepointComp.js-meta.xml
- force-app/main/default/objects/Sharepoint_Setting__c/Sharepoint_Setting__c.object-meta.xml
- force-app/main/default/objects/Sharepoint_Setting__c/fields/drive_id_secure__c.field-meta.xml
> [DevOps Center] Merge UAT to Production

- force-app/main/default/flows/Case_Individual_Client_Acceptance_Form.flow-meta.xml
> [DevOps Center] Merge WI-000949 to Integration

- force-app/main/default/flows/Case_Individual_Client_Acceptance_Form.flow-meta.xml
> [DevOps Center] Merge WI-000949 to UAT

- force-app/main/default/flexipages/Account_Record_Page.flexipage-meta.xml
> [DevOps Center] Merge WI-000950 to Integration

- force-app/main/default/flexipages/Account_Record_Page.flexipage-meta.xml
> [DevOps Center] Merge WI-000950 to UAT

- force-app/main/default/flexipages/Audit_Register_Record_Page.flexipage-meta.xml
- force-app/main/default/flows/Audit_Register_On_Create.flow-meta.xml
- force-app/main/default/objects/Audit_Register__c/fields/Audit_Fee__c.field-meta.xml
- force-app/main/default/objects/Audit_Register__c/fields/CP_Filing_accounts_on_behalf__c.field-meta.xml
- force-app/main/default/objects/Audit_Register__c/fields/Date_Accounts_Sent_to_Companies_House__c.field-meta.xml
- force-app/main/default/objects/Audit_Register__c/fields/Date_acknowledgement_received__c.field-meta.xml
- force-app/main/default/objects/Audit_Register__c/fields/Date_submitted_online_via_CaseWare__c.field-meta.xml
- force-app/main/default/objects/Audit_Register__c/fields/Investment_Amount__c.field-meta.xml
- force-app/main/default/objects/Audit_Register__c/fields/Year_End__c.field-meta.xml
> [DevOps Center] Merge WI-000952 to Integration

- force-app/main/default/flexipages/Audit_Register_Record_Page.flexipage-meta.xml
- force-app/main/default/flows/Audit_Register_On_Create.flow-meta.xml
- force-app/main/default/objects/Audit_Register__c/fields/Audit_Fee__c.field-meta.xml
- force-app/main/default/objects/Audit_Register__c/fields/CP_Filing_accounts_on_behalf__c.field-meta.xml
- force-app/main/default/objects/Audit_Register__c/fields/Date_Accounts_Sent_to_Companies_House__c.field-meta.xml
- force-app/main/default/objects/Audit_Register__c/fields/Date_acknowledgement_received__c.field-meta.xml
- force-app/main/default/objects/Audit_Register__c/fields/Date_submitted_online_via_CaseWare__c.field-meta.xml
- force-app/main/default/objects/Audit_Register__c/fields/Investment_Amount__c.field-meta.xml
- force-app/main/default/objects/Audit_Register__c/fields/Year_End__c.field-meta.xml
> [DevOps Center] Merge WI-000952 to UAT

- force-app/main/default/classes/BatchCreateSharepointFolderCase.cls
- force-app/main/default/classes/SharepointCompCont.cls
- force-app/main/default/classes/SharepointUploadFileInvocable.cls
- force-app/main/default/classes/SharepointUploadFileInvocableTest.cls
- force-app/main/default/classes/SmartSearchCompCont.cls
- force-app/main/default/classes/SmartSearchCompContTest.cls
- force-app/main/default/classes/SmartSearchCompContTest.cls-meta.xml
- force-app/main/default/lwc/sharepointComp/sharepointComp.html
- force-app/main/default/lwc/sharepointComp/sharepointComp.js
> [DevOps Center] Merge WI-000953 to Integration

- force-app/main/default/classes/BatchCreateSharepointFolderCase.cls
- force-app/main/default/classes/SharepointCompCont.cls
- force-app/main/default/classes/SharepointUploadFileInvocable.cls
- force-app/main/default/classes/SharepointUploadFileInvocableTest.cls
- force-app/main/default/classes/SmartSearchCompCont.cls
- force-app/main/default/classes/SmartSearchCompContTest.cls
- force-app/main/default/classes/SmartSearchCompContTest.cls-meta.xml
- force-app/main/default/lwc/sharepointComp/sharepointComp.html
- force-app/main/default/lwc/sharepointComp/sharepointComp.js
> [DevOps Center] Merge WI-000953 to UAT

- force-app/main/default/permissionsets/Access_Setup.permissionset-meta.xml
> [DevOps Center] Merge WI-000954 to Integration

- force-app/main/default/permissionsets/Access_Setup.permissionset-meta.xml
> [DevOps Center] Merge WI-000954 to UAT

- force-app/main/default/flexipages/Account_Record_Page.flexipage-meta.xml
> [DevOps Center] Merge WI-000955 to Integration

- force-app/main/default/classes/SharepointCompCont.cls
- force-app/main/default/lwc/sharepointComp/sharepointComp.js
> [DevOps Center] Merge WI-000956 to Integration

- force-app/main/default/classes/SharepointCompCont.cls
- force-app/main/default/lwc/sharepointComp/sharepointComp.js
> [DevOps Center] Merge WI-000956 to UAT

- force-app/main/default/classes/BeauhurstAPIUtility.cls
- force-app/main/default/classes/BeauhurstAPIUtility.cls-meta.xml
- force-app/main/default/classes/GetCompanyIdBatch.cls
- force-app/main/default/classes/GetCompanyIdBatch.cls-meta.xml
- force-app/main/default/classes/UpdateAccountsFromBHBatch.cls
- force-app/main/default/classes/UpdateAccountsFromBHBatch.cls-meta.xml
> [DevOps Center] Merge WI-000958 to Integration

- force-app/main/default/classes/CPNoteHTMLControllerTest.cls
- force-app/main/default/classes/CPNoteHTMLControllerTest.cls-meta.xml
> [DevOps Center] Merge WI-000960 to UAT

- force-app/main/default/classes/BeauhurstAPIUtility.cls
- force-app/main/default/classes/BeauhurstAPIUtility.cls-meta.xml
- force-app/main/default/classes/GetCompanyIdBatch.cls
- force-app/main/default/classes/GetCompanyIdBatch.cls-meta.xml
- force-app/main/default/classes/UpdateAccountsFromBHBatch.cls
- force-app/main/default/classes/UpdateAccountsFromBHBatch.cls-meta.xml
> [DevOps Center] Merge WI-000958 to UAT

- force-app/main/default/flexipages/Account_Record_Page.flexipage-meta.xml
> [DevOps Center] Merge WI-000961 to Integration

- force-app/main/default/flows/Case_Individual_Client_Acceptance_Form.flow-meta.xml
- force-app/main/default/objects/Client_Acceptance_Form__c/fields/Full_Name2__c.field-meta.xml
- force-app/main/default/objects/Client_Acceptance_Form__c/fields/ID_verified_by2__c.field-meta.xml
> [DevOps Center] Merge WI-000962 to Integration

- force-app/main/default/flows/Case_Individual_Client_Acceptance_Form.flow-meta.xml
- force-app/main/default/objects/Client_Acceptance_Form__c/fields/Full_Name2__c.field-meta.xml
- force-app/main/default/objects/Client_Acceptance_Form__c/fields/ID_verified_by2__c.field-meta.xml
> [DevOps Center] Merge WI-000962 to UAT

- force-app/main/default/flexipages/Account_Record_Page.flexipage-meta.xml
> [DevOps Center] Merge WI-000963 to Integration

- force-app/main/default/classes/BeauhurstAPIUtility.cls
- force-app/main/default/classes/UpdateAccountsFromBHBatch.cls
> [DevOps Center] Merge WI-000964 to Integration

- force-app/main/default/classes/BeauhurstAPIUtility.cls
- force-app/main/default/classes/GetCompanyIdBatch.cls
- force-app/main/default/classes/UpdateAccountsFromBHBatch.cls
> [DevOps Center] Merge WI-000965 to Integration

- force-app/main/default/classes/BeauhurstAPIUtility.cls
- force-app/main/default/classes/GetCompanyIdBatch.cls
- force-app/main/default/classes/UpdateAccountsFromBHBatch.cls
> [DevOps Center] Merge WI-000965 to UAT

- force-app/main/default/classes/CreateAccountsFromBHBatch.cls
- force-app/main/default/classes/CreateAccountsFromBHBatch.cls-meta.xml
- force-app/main/default/classes/UpdateAccountsFromBHBatch.cls
> [DevOps Center] Merge WI-000966 to Integration

- force-app/main/default/flexipages/Account_Record_Page.flexipage-meta.xml
> [DevOps Center] Merge WI-000963 to UAT

- force-app/main/default/flows/Case_Client_Acceptance_Form.flow-meta.xml
- force-app/main/default/flows/Case_Individual_Client_Acceptance_Form.flow-meta.xml
- force-app/main/default/objects/Client_Acceptance_Form__c/fields/Are_there_any_other_relationships_Text__c.field-meta.xml
- force-app/main/default/objects/Client_Acceptance_Form__c/fields/Current_Adviser_Response__c.field-meta.xml
- force-app/main/default/objects/Client_Acceptance_Form__c/fields/Do_we_have_any_concerns_Exp__c.field-meta.xml
- force-app/main/default/objects/Client_Acceptance_Form__c/fields/Fees_agreed_with_client_Pick__c.field-meta.xml
- force-app/main/default/objects/Client_Acceptance_Form__c/fields/Has_a_business_SmartSearch__c.field-meta.xml
- force-app/main/default/objects/Client_Acceptance_Form__c/fields/Have_you_made_enquiry_s_as_to_the_source__c.field-meta.xml
- force-app/main/default/objects/Client_Acceptance_Form__c/fields/Have_you_reviewed_all_annual_returns__c.field-meta.xml
- force-app/main/default/objects/Client_Acceptance_Form__c/fields/List_all_services_included_in_this_onboa__c.field-meta.xml
- force-app/main/default/objects/Client_Acceptance_Form__c/fields/Office__c.field-meta.xml
- force-app/main/default/objects/Client_Acceptance_Form__c/fields/Please_give_details_of_individuals_we__c.field-meta.xml
- force-app/main/default/objects/Client_Acceptance_Form__c/fields/Please_state_which_team_member_has_met__c.field-meta.xml
- force-app/main/default/objects/Client_Acceptance_Form__c/fields/Reason_for_Change_and_Intro_to_CP__c.field-meta.xml
- force-app/main/default/objects/Client_Acceptance_Form__c/fields/regpick20__c.field-meta.xml
> [DevOps Center] Merge WI-000967 to Integration

- force-app/main/default/flows/Case_Client_Acceptance_Form.flow-meta.xml
- force-app/main/default/flows/Case_Individual_Client_Acceptance_Form.flow-meta.xml
- force-app/main/default/objects/Client_Acceptance_Form__c/fields/Are_there_any_other_relationships_Text__c.field-meta.xml
- force-app/main/default/objects/Client_Acceptance_Form__c/fields/Current_Adviser_Response__c.field-meta.xml
- force-app/main/default/objects/Client_Acceptance_Form__c/fields/Do_we_have_any_concerns_Exp__c.field-meta.xml
- force-app/main/default/objects/Client_Acceptance_Form__c/fields/Fees_agreed_with_client_Pick__c.field-meta.xml
- force-app/main/default/objects/Client_Acceptance_Form__c/fields/Has_a_business_SmartSearch__c.field-meta.xml
- force-app/main/default/objects/Client_Acceptance_Form__c/fields/Have_you_made_enquiry_s_as_to_the_source__c.field-meta.xml
- force-app/main/default/objects/Client_Acceptance_Form__c/fields/Have_you_reviewed_all_annual_returns__c.field-meta.xml
- force-app/main/default/objects/Client_Acceptance_Form__c/fields/List_all_services_included_in_this_onboa__c.field-meta.xml
- force-app/main/default/objects/Client_Acceptance_Form__c/fields/Office__c.field-meta.xml
- force-app/main/default/objects/Client_Acceptance_Form__c/fields/Please_give_details_of_individuals_we__c.field-meta.xml
- force-app/main/default/objects/Client_Acceptance_Form__c/fields/Please_state_which_team_member_has_met__c.field-meta.xml
- force-app/main/default/objects/Client_Acceptance_Form__c/fields/Reason_for_Change_and_Intro_to_CP__c.field-meta.xml
- force-app/main/default/objects/Client_Acceptance_Form__c/fields/regpick20__c.field-meta.xml
> [DevOps Center] Merge WI-000967 to UAT

- force-app/main/default/flows/Opportunity_Update_Naming_Convention.flow-meta.xml
> [DevOps Center] Merge WI-000969 to Integration

- force-app/main/default/flows/Opportunity_Update_Naming_Convention.flow-meta.xml
> [DevOps Center] Merge WI-000969 to UAT

- force-app/main/default/classes/UpdateAccountsFromBHBatchTest.cls
> [DevOps Center] Merge WI-000971 to Integration

- force-app/main/default/classes/UpdateAccountsFromBHBatchTest.cls
> [DevOps Center] Merge WI-000971 to UAT

- force-app/main/default/flexipages/Audit_Register_Record_Page.flexipage-meta.xml
- force-app/main/default/layouts/Audit_Register__c-Audit Register Layout.layout-meta.xml
- force-app/main/default/objects/Audit_Register__c/fields/Length_of_RI_Service__c.field-meta.xml
> [DevOps Center] Merge WI-000970 to Integration

- force-app/main/default/flexipages/Audit_Register_Record_Page.flexipage-meta.xml
- force-app/main/default/layouts/Audit_Register__c-Audit Register Layout.layout-meta.xml
- force-app/main/default/objects/Audit_Register__c/fields/Length_of_RI_Service__c.field-meta.xml
> [DevOps Center] Merge WI-000970 to UAT

- force-app/main/default/classes/UpdateAccountsFromBHBatch.cls
> [DevOps Center] Merge WI-000976 to Integration

- force-app/main/default/classes/UpdateAccountsFromBHBatch.cls
> [DevOps Center] Merge WI-000976 to UAT

- force-app/main/default/flows/Opportunity_TAX_Estimates_Validation_Rule.flow-meta.xml
> [DevOps Center] Merge WI-000979 to Integration

- force-app/main/default/flows/Opportunity_TAX_Estimates_Validation_Rule.flow-meta.xml
> [DevOps Center] Merge WI-000979 to UAT

- force-app/main/default/flexipages/Account_Record_Page.flexipage-meta.xml
> [DevOps Center] Merge WI-000981 to Integration

- force-app/main/default/flexipages/Account_Record_Page.flexipage-meta.xml
> [DevOps Center] Merge WI-000981 to UAT

- force-app/main/default/flows/Case_BTNC_Continuation_Form.flow-meta.xml
- force-app/main/default/flows/Individual_Ongoing_Monitoring.flow-meta.xml
> [DevOps Center] Merge WI-000983 to Integration

- force-app/main/default/classes/BatchCreateSharepointFolderAccount.cls
> [DevOps Center] Merge WI-000986 to Integration

- force-app/main/default/flows/Case_Submit_For_CAF_Form_Approval.flow-meta.xml
- force-app/main/default/objects/Case/validationRules/V7_Client_Amendment_Requirement.validationRule-meta.xml
> [DevOps Center] Merge WI-000989 to Integration

- force-app/main/default/flows/Account_Populate_Stamp_Data_Origination.flow-meta.xml
- force-app/main/default/objects/Account/fields/Stamp_Data_Origination__c.field-meta.xml
> [DevOps Center] Merge WI-000990 to Integration

- force-app/main/default/flows/Account_Populate_Stamp_Data_Origination.flow-meta.xml
> [DevOps Center] Merge WI-000991 to Integration

- force-app/main/default/flows/Account_Inactive_Validation.flow-meta.xml
- force-app/main/default/flows/Account_Lock_Inactive_Account.flow-meta.xml
> [DevOps Center] Merge WI-000992 to Integration

- force-app/main/default/flexipages/Audit_Register_Record_Page.flexipage-meta.xml
- force-app/main/default/layouts/Audit_Register__c-Audit Register Layout.layout-meta.xml
- force-app/main/default/objects/Audit_Register__c/fields/Audit_Register_Completed__c.field-meta.xml
- force-app/main/default/objects/Audit_Register__c/fields/CP_Client_Code__c.field-meta.xml
- force-app/main/default/objects/Audit_Register__c/fields/CW_lockdown_Date__c.field-meta.xml
> [DevOps Center] Merge WI-000993 to Integration

- force-app/main/default/objects/Account/fields/Data_Origination__c.field-meta.xml
> [DevOps Center] Merge WI-000994 to Integration

- force-app/main/default/flows/Account_Inactive_Validation.flow-meta.xml
- force-app/main/default/flows/Account_Lock_Inactive_Account.flow-meta.xml
> [DevOps Center] Merge WI-000995 to Integration

- force-app/main/default/globalValueSets/Type_of_Business.globalValueSet-meta.xml
- force-app/main/default/objects/CP_Note__c/fields/Type__c.field-meta.xml
> [DevOps Center] Merge WI-000998 to Integration

- force-app/main/default/flows/Case_Risk_Team_Validation.flow-meta.xml
> [DevOps Center] Merge WI-000999 to Integration

- force-app/main/default/flexipages/Account_Record_Page.flexipage-meta.xml
> [DevOps Center] Merge WI-001000 to Integration

- force-app/main/default/flexipages/Person_Account_Record_Page.flexipage-meta.xml
- force-app/main/default/objects/CP_Note__c/CP_Note__c.object-meta.xml
> [DevOps Center] Merge WI-001001 to Integration

- force-app/main/default/flows/Account_Risk_Team_Validation.flow-meta.xml
> [DevOps Center] Merge WI-001002 to Integration

- force-app/main/default/flexipages/Account_Record_Page.flexipage-meta.xml
- force-app/main/default/flexipages/Person_Account_Record_Page.flexipage-meta.xml
> [DevOps Center] Merge WI-001003 to Integration

- force-app/main/default/permissionsets/Manage_Approvals_Permission.permissionset-meta.xml
> [DevOps Center] Merge WI-001005 to Integration

- force-app/main/default/permissionsets/View_All_Data.permissionset-meta.xml
> [DevOps Center] Merge WI-001006 to Integration

- force-app/main/default/objects/Case/validationRules/V8_Engagement_Pack_Approval.validationRule-meta.xml
> [DevOps Center] Merge WI-001007 to Integration

- force-app/main/default/objects/Case/validationRules/V8_Engagement_Pack_Approval.validationRule-meta.xml
> [DevOps Center] Merge WI-001007 to UAT

- force-app/main/default/globalValueSets/Lead_Area.globalValueSet-meta.xml
> [DevOps Center] Merge WI-001008 to Integration

- force-app/main/default/flexipages/Audit_Register_Record_Page.flexipage-meta.xml
> [DevOps Center] Merge WI-001009 to Integration

- force-app/main/default/globalValueSets/Lead_Area.globalValueSet-meta.xml
> [DevOps Center] Merge WI-001008 to UAT

- force-app/main/default/flexipages/Audit_Register_Record_Page.flexipage-meta.xml
> [DevOps Center] Merge WI-001009 to UAT

- force-app/main/default/flows/Opportunity_Submit_to_THG_Audit_Resourcing_Approval.flow-meta.xml
- force-app/main/default/flows/Opportunity_THG_Audit_Partner_Approval.flow-meta.xml
- force-app/main/default/flows/Opportunity_THG_Audit_Resourcing_Approval.flow-meta.xml
- force-app/main/default/objects/Opportunity/fields/Resourcing_Team_Required__c.field-meta.xml
- force-app/main/default/objects/Opportunity/validationRules/V3_Resourcing_Team_Required.validationRule-meta.xml
> [DevOps Center] Merge WI-001011 to Integration

- force-app/main/default/flows/Opportunity_Submit_to_THG_Audit_Resourcing_Approval.flow-meta.xml
- force-app/main/default/flows/Opportunity_THG_Audit_Partner_Approval.flow-meta.xml
- force-app/main/default/flows/Opportunity_THG_Audit_Resourcing_Approval.flow-meta.xml
- force-app/main/default/objects/Opportunity/fields/Resourcing_Team_Required__c.field-meta.xml
- force-app/main/default/objects/Opportunity/validationRules/V3_Resourcing_Team_Required.validationRule-meta.xml
> [DevOps Center] Merge WI-001011 to UAT

- force-app/main/default/objects/Opportunity/validationRules/V3_Resourcing_Team_Required.validationRule-meta.xml
> [DevOps Center] Merge WI-001012 to Integration

- force-app/main/default/objects/Opportunity/validationRules/V3_Resourcing_Team_Required.validationRule-meta.xml
> [DevOps Center] Merge WI-001012 to UAT

- force-app/main/default/globalValueSets/Service_Lines.globalValueSet-meta.xml
> [DevOps Center] Merge WI-001013 to Integration

- force-app/main/default/globalValueSets/Service_Lines.globalValueSet-meta.xml
> [DevOps Center] Merge WI-001013 to UAT

- force-app/main/default/flexipages/Account_Record_Page.flexipage-meta.xml
- force-app/main/default/flexipages/Person_Account_Record_Page.flexipage-meta.xml
> [DevOps Center] Merge WI-001014 to Integration

- force-app/main/default/flexipages/Account_Record_Page.flexipage-meta.xml
- force-app/main/default/flexipages/Person_Account_Record_Page.flexipage-meta.xml
> [DevOps Center] Merge WI-001014 to UAT

- force-app/main/default/flexipages/Account_Record_Page.flexipage-meta.xml
- force-app/main/default/flexipages/Person_Account_Record_Page.flexipage-meta.xml
> [DevOps Center] Merge WI-001018 to Integration

- force-app/main/default/flexipages/Account_Record_Page.flexipage-meta.xml
- force-app/main/default/flexipages/Person_Account_Record_Page.flexipage-meta.xml
> [DevOps Center] Merge WI-001018 to UAT

- force-app/main/default/globalValueSets/DocuSign_Document_Sub_List.globalValueSet-meta.xml
- force-app/main/default/objects/Account/fields/DocuSign_Document_Sub_List_Cont__c.field-meta.xml
- force-app/main/default/objects/Account/fields/DocuSign_Document_Sub_List__c.field-meta.xml
- force-app/main/default/objects/Account/fields/DocuSign_Documents_Cont__c.field-meta.xml
> [DevOps Center] Merge WI-001020 to Integration

- force-app/main/default/globalValueSets/DocuSign_Document_Sub_List.globalValueSet-meta.xml
- force-app/main/default/objects/Account/fields/DocuSign_Document_Sub_List_Cont__c.field-meta.xml
- force-app/main/default/objects/Account/fields/DocuSign_Document_Sub_List__c.field-meta.xml
- force-app/main/default/objects/Account/fields/DocuSign_Documents_Cont__c.field-meta.xml
> [DevOps Center] Merge WI-001020 to UAT

- force-app/main/default/globalValueSets/DocuSign_Document_Sub_List.globalValueSet-meta.xml
- force-app/main/default/objects/Account/fields/DocuSign_Document_Sub_List_Cont__c.field-meta.xml
> [DevOps Center] Merge WI-001021 to Integration

- force-app/main/default/globalValueSets/DocuSign_Document_Sub_List.globalValueSet-meta.xml
- force-app/main/default/objects/Account/fields/DocuSign_Document_Sub_List_Cont__c.field-meta.xml
> [DevOps Center] Merge WI-001021 to UAT

- force-app/main/default/flexipages/Account_Record_Page.flexipage-meta.xml
- force-app/main/default/flexipages/Person_Account_Record_Page.flexipage-meta.xml
> [DevOps Center] Merge WI-001024 to Integration

- force-app/main/default/flexipages/Account_Record_Page.flexipage-meta.xml
- force-app/main/default/flexipages/Person_Account_Record_Page.flexipage-meta.xml
> [DevOps Center] Merge WI-001024 to UAT

- force-app/main/default/objects/Account/fields/DocuSign_Document_Sub_List_Cont__c.field-meta.xml
- force-app/main/default/objects/Account/fields/DocuSign_Document_Sub_List__c.field-meta.xml
> [DevOps Center] Merge WI-001023 to UAT

- force-app/main/default/objects/Contact/fields/pse__Resource_Role__c.field-meta.xml
- force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
> [DevOps Center] Merge WI-001025 to Integration

- force-app/main/default/objects/Account/recordTypes/Business_Account.recordType-meta.xml
- force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
> [DevOps Center] Merge WI-001022 to Integration

- force-app/main/default/objects/Account/fields/DocuSign_Document_Sub_List_Cont__c.field-meta.xml
> [DevOps Center] Merge WI-001026 to Integration

- force-app/main/default/objects/Account/fields/DocuSign_Document_Sub_List_Cont__c.field-meta.xml
> [DevOps Center] Merge WI-001026 to UAT

- force-app/main/default/globalValueSets/DocuSign_Document_Sub_List.globalValueSet-meta.xml
> [DevOps Center] Merge WI-001027 to Integration

- force-app/main/default/globalValueSets/DocuSign_Document_Sub_List.globalValueSet-meta.xml
> [DevOps Center] Merge WI-001027 to UAT

- force-app/main/default/classes/BatchCreateSharepointFolderAccount.cls
> [DevOps Center] Merge WI-001028 to UAT

- force-app/main/default/matchingRules/Account.matchingRule-meta.xml
> [DevOps Center] Merge WI-001030 to Integration

- force-app/main/default/duplicateRules/Account.Account_Account_Name.duplicateRule-meta.xml
> [DevOps Center] Merge WI-001031 to Integration

- force-app/main/default/matchingRules/Account.matchingRule-meta.xml
> [DevOps Center] Merge WI-001030 to UAT

- force-app/main/default/objects/Contact/fields/Advocacy_Survey_Send_Month__c.field-meta.xml
- force-app/main/default/objects/Contact/fields/Contact_added_to_Campaign__c.field-meta.xml
- force-app/main/default/objects/Contact/fields/Current_How_are_we_doing__c.field-meta.xml
- force-app/main/default/objects/Contact/fields/Field_Advocacy_Survey_Send_Month_Calc__c.field-meta.xml
- force-app/main/default/objects/Contact/fields/How_likely_is_it_you_would_recommend_CP__c.field-meta.xml
- force-app/main/default/objects/Contact/fields/Should_be_sent_survey__c.field-meta.xml
- force-app/main/default/objects/Contact/fields/Tell_us_why_you_ve_chosen_this_rating__c.field-meta.xml
> [DevOps Center] Merge WI-001032 to Integration

- force-app/main/default/objects/Contact/fields/Advocacy_Survey_Send_Month__c.field-meta.xml
- force-app/main/default/objects/Contact/fields/Contact_added_to_Campaign__c.field-meta.xml
- force-app/main/default/objects/Contact/fields/Current_How_are_we_doing__c.field-meta.xml
- force-app/main/default/objects/Contact/fields/Field_Advocacy_Survey_Send_Month_Calc__c.field-meta.xml
- force-app/main/default/objects/Contact/fields/How_likely_is_it_you_would_recommend_CP__c.field-meta.xml
- force-app/main/default/objects/Contact/fields/Should_be_sent_survey__c.field-meta.xml
- force-app/main/default/objects/Contact/fields/Tell_us_why_you_ve_chosen_this_rating__c.field-meta.xml
> [DevOps Center] Merge WI-001032 to UAT

- force-app/main/default/flows/Case_BTNC_Continuation_Form.flow-meta.xml
- force-app/main/default/flows/Case_Client_Acceptance_Form.flow-meta.xml
- force-app/main/default/flows/Case_Individual_Client_Acceptance_Form.flow-meta.xml
- force-app/main/default/objects/Client_Acceptance_Form__c/fields/Do_we_have_any_concerns_Exp2__c.field-meta.xml
- force-app/main/default/objects/Client_Acceptance_Form__c/fields/Safeguards_Applied__c.field-meta.xml
- force-app/main/default/objects/Client_Acceptance_Form__c/fields/pickfin1__c.field-meta.xml
> [DevOps Center] Merge WI-001034 to Integration

- force-app/main/default/flows/Case_BTNC_Continuation_Form.flow-meta.xml
- force-app/main/default/flows/Case_Client_Acceptance_Form.flow-meta.xml
- force-app/main/default/flows/Case_Individual_Client_Acceptance_Form.flow-meta.xml
- force-app/main/default/objects/Client_Acceptance_Form__c/fields/Do_we_have_any_concerns_Exp2__c.field-meta.xml
- force-app/main/default/objects/Client_Acceptance_Form__c/fields/Safeguards_Applied__c.field-meta.xml
- force-app/main/default/objects/Client_Acceptance_Form__c/fields/pickfin1__c.field-meta.xml
> [DevOps Center] Merge WI-001034 to UAT

- force-app/main/default/flows/Case_Individual_Client_Acceptance_Form.flow-meta.xml
> [DevOps Center] Merge WI-001035 to Integration

- force-app/main/default/flexipages/Account_Record_Page.flexipage-meta.xml
> [DevOps Center] Merge WI-001039 to Integration

- force-app/main/default/flows/Case_BTNC_Continuation_Form.flow-meta.xml
> [DevOps Center] Merge WI-001037 to Integration

- force-app/main/default/objects/Account/validationRules/V7_DocuSign_SubList.validationRule-meta.xml
> [DevOps Center] Merge WI-001038 to Integration

- force-app/main/default/objects/ffpsai__ExpenseTypeGLAMapping__c/fields/ffpsai__ExpenseType__c.field-meta.xml
- force-app/main/default/objects/ffscpq__Estimated_Expense__c/fields/ffscpq__Type__c.field-meta.xml
- force-app/main/default/objects/pse__Expense_Limit_Rate__c/fields/pse__Type__c.field-meta.xml
- force-app/main/default/objects/pse__Expense__c/fields/pse__Type__c.field-meta.xml
> [DevOps Center] Merge WI-001040 to Integration

- force-app/main/default/classes/AccountTriggerHandler.cls
- force-app/main/default/classes/AccountTriggerHandler.cls-meta.xml
- force-app/main/default/classes/BeauhurstAPIUtility.cls
- force-app/main/default/classes/CreateAccountsFromBHBatch.cls
- force-app/main/default/classes/CreateAccountsFromBHBatchTest.cls
- force-app/main/default/classes/GetCompanyIdBatch.cls
- force-app/main/default/classes/UpdateAccountsFromBHBatch.cls
> [DevOps Center] Merge WI-001042 to Integration

- force-app/main/default/classes/GetCompanyIdBatch.cls
- force-app/main/default/classes/UpdateAccountsFromBHBatch.cls
> [DevOps Center] Merge WI-001044 to Integration

- force-app/main/default/flexipages/Opportunity_Record_Page.flexipage-meta.xml
> [DevOps Center] Merge WI-001047 to Integration

- force-app/main/default/objects/Case/fields/Closed_Reason__c.field-meta.xml
- force-app/main/default/objects/Case/recordTypes/Onboarding.recordType-meta.xml
> [DevOps Center] Merge WI-001048 to Integration

- force-app/main/default/objects/Case/fields/Closed_Reason__c.field-meta.xml
- force-app/main/default/objects/Case/recordTypes/Onboarding.recordType-meta.xml
> [DevOps Center] Merge WI-001048 to UAT

- force-app/main/default/flows/Account_Team_Member_Add_Name.flow-meta.xml
> [DevOps Center] Merge WI-001051 to Integration

- force-app/main/default/flexipages/Person_Account_Record_Page.flexipage-meta.xml
> [DevOps Center] Merge WI-001052 to Integration

- force-app/main/default/objects/Case/fields/Closed_Reason__c.field-meta.xml
> [DevOps Center] Merge WI-001053 to Integration

- force-app/main/default/flows/Opportunity_Audit_Estimate_Validation.flow-meta.xml
> [DevOps Center] Merge WI-001054 to Integration

- force-app/main/default/objects/Case/fields/Closed_Reason__c.field-meta.xml
> [DevOps Center] Merge WI-001053 to UAT

- force-app/main/default/flows/Opportunity_Audit_Estimate_Validation.flow-meta.xml
> [DevOps Center] Merge WI-001054 to UAT

- force-app/main/default/objects/Opportunity/validationRules/V3_Resourcing_Team_Required.validationRule-meta.xml
> [DevOps Center] Merge WI-001055 to UAT

- force-app/main/default/classes/CSVRecordUploaderController.cls
- force-app/main/default/classes/CSVRecordUploaderController.cls-meta.xml
- force-app/main/default/customMetadata/Uploader_Mapping.CP_Office.md-meta.xml
- force-app/main/default/customMetadata/Uploader_Mapping.Data_Origination_ID.md-meta.xml
- force-app/main/default/customMetadata/Uploader_Mapping.Primary_Sector.md-meta.xml
- force-app/main/default/customMetadata/Uploader_Mapping.Type_Of_Business.md-meta.xml
- force-app/main/default/customMetadata/Uploader_Mapping.UK_Registered_Entity.md-meta.xml
- force-app/main/default/lwc/cSVRecordUploader/cSVRecordUploader.css
- force-app/main/default/lwc/cSVRecordUploader/cSVRecordUploader.html
- force-app/main/default/lwc/cSVRecordUploader/cSVRecordUploader.js
- force-app/main/default/lwc/cSVRecordUploader/cSVRecordUploader.js-meta.xml
> [DevOps Center] Merge WI-001060 to Integration

- force-app/main/default/permissionsetgroups/Cooper_Parry_PSG_PMs_Resourcing.permissionsetgroup-meta.xml
- force-app/main/default/permissionsets/Cooper_Parry_PSA_Permission_Set.permissionset-meta.xml
> [DevOps Center] Merge WI-001062 to Integration

- force-app/main/default/globalValueSets/DocuSign_Document_Sub_List.globalValueSet-meta.xml
> [DevOps Center] Merge WI-001067 to Integration

- force-app/main/default/flexipages/Corporate_Opp_Record_Page.flexipage-meta.xml
> [DevOps Center] Merge WI-001068 to Integration

- force-app/main/default/classes/CompaniesHouse_AccountFieldMapping.cls
> [DevOps Center] Merge WI-001069 to Integration

- force-app/main/default/classes/CompaniesHouse_AccountFieldMapping.cls
> [DevOps Center] Merge WI-001070 to Integration

- force-app/main/default/email/CPTemplates/Embed_a_Survey_Link.email
- force-app/main/default/email/CPTemplates/Embed_a_Survey_Link.email-meta.xml
- force-app/main/default/email/CPTemplates/Embed_a_Survey_Link_Reminder_1_1736441886233.email
- force-app/main/default/email/CPTemplates/Embed_a_Survey_Link_Reminder_1_1736441886233.email-meta.xml
- force-app/main/default/email/CPTemplates/Survey_NPS_Email_Template_1736331435158.email
- force-app/main/default/email/CPTemplates/Survey_NPS_Email_Template_1736331435158.email-meta.xml
> [DevOps Center] Merge WI-001066 to Integration

- force-app/main/default/email/CPTemplates/Embed_a_Survey_Link.email
- force-app/main/default/email/CPTemplates/Embed_a_Survey_Link.email-meta.xml
- force-app/main/default/email/CPTemplates/Embed_a_Survey_Link_Reminder_1_1736441886233.email
- force-app/main/default/email/CPTemplates/Embed_a_Survey_Link_Reminder_1_1736441886233.email-meta.xml
- force-app/main/default/email/CPTemplates/Survey_NPS_Email_Template_1736331435158.email
- force-app/main/default/email/CPTemplates/Survey_NPS_Email_Template_1736331435158.email-meta.xml
> [DevOps Center] Merge WI-001066 to UAT

- force-app/main/default/objects/Account/fields/Sharepoint_Public_URL__c.field-meta.xml
- force-app/main/default/objects/Account/fields/Sharepoint_Secured_URL__c.field-meta.xml
> [DevOps Center] Merge WI-001074 to Integration

- force-app/main/default/flexipages/ProjectLightningPage1.flexipage-meta.xml
- force-app/main/default/flows/CT_Update_Project_region_from_Partner_Partner_s_region.flow-meta.xml
> [DevOps Center] Merge WI-001079 to Integration

- force-app/main/default/objects/Account/validationRules/V8_Type_Client.validationRule-meta.xml
> [DevOps Center] Merge WI-001075 to Integration

- force-app/main/default/permissionsets/Onboarding_Completed_Edit_Access.permissionset-meta.xml
> [DevOps Center] Merge WI-001080 to Integration

- force-app/main/default/permissionsets/Case_Permission_Delete.permissionset-meta.xml
> [DevOps Center] Merge WI-001081 to Integration

- force-app/main/default/objects/AccountTeamMember/fields/Delete__c.field-meta.xml
> [DevOps Center] Merge WI-001083 to Integration

- force-app/main/default/objects/Client_Acceptance_Form__c/fields/Confirm_that_we_have_ascertained_the_tax__c.field-meta.xml
> [DevOps Center] Merge WI-001084 to Integration

- force-app/main/default/permissionsets/Date_Became_Client_Edit_Access.permissionset-meta.xml
> [DevOps Center] Merge WI-001086 to Integration

- force-app/main/default/flexipages/Account_Record_Page.flexipage-meta.xml
- force-app/main/default/flexipages/Person_Account_Record_Page.flexipage-meta.xml
- force-app/main/default/layouts/Account-CP Account Layout.layout-meta.xml
- force-app/main/default/objects/Account/fields/BH_Audit_Fee__c.field-meta.xml
> [DevOps Center] Merge WI-001087 to Integration

- force-app/main/default/flexipages/Account_Record_Page.flexipage-meta.xml
- force-app/main/default/flexipages/Person_Account_Record_Page.flexipage-meta.xml
- force-app/main/default/layouts/Account-CP Account Layout.layout-meta.xml
- force-app/main/default/objects/Account/fields/BH_Audit_Fee__c.field-meta.xml
> [DevOps Center] Merge WI-001087 to UAT

- force-app/main/default/globalValueSets/DocuSign_Document_Sub_List.globalValueSet-meta.xml
- force-app/main/default/objects/Account/recordTypes/Business_Account.recordType-meta.xml
- force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
> [DevOps Center] Merge WI-001089 to Integration

- force-app/main/default/flows/Opportunity_Audit_Estimate_Validation.flow-meta.xml
> [DevOps Center] Merge WI-001090 to Integration

- force-app/main/default/flows/Opportunity_Audit_Estimate_Validation.flow-meta.xml
> [DevOps Center] Merge WI-001090 to UAT

- force-app/main/default/flows/firm_wide_survey.flow-meta.xml
> [DevOps Center] Merge WI-001091 to Integration

- force-app/main/default/flows/firm_wide_survey.flow-meta.xml
> [DevOps Center] Merge WI-001091 to UAT

- force-app/main/default/classes/SurveyInvitationTriggerHandler.cls
- force-app/main/default/flows/Survey_Invitation_Scheduled_Flow_Send_Follow_up_Survey_Invitations.flow-meta.xml
- force-app/main/default/objects/SurveyInvitation/fields/Created_Date_Custom__c.field-meta.xml
- force-app/main/default/triggers/SurveyInvitationTrigger.trigger
> [DevOps Center] Merge WI-001093 to Integration

- force-app/main/default/classes/SurveyInvitationTriggerHandler.cls
- force-app/main/default/flows/Survey_Invitation_Scheduled_Flow_Send_Follow_up_Survey_Invitations.flow-meta.xml
- force-app/main/default/objects/SurveyInvitation/fields/Created_Date_Custom__c.field-meta.xml
- force-app/main/default/triggers/SurveyInvitationTrigger.trigger
> [DevOps Center] Merge WI-001093 to UAT

- force-app/main/default/flows/Survey_Adding_Campaign_Members.flow-meta.xml
> [DevOps Center] Merge WI-001094 to Integration

- force-app/main/default/flows/Survey_Adding_Campaign_Members.flow-meta.xml
> [DevOps Center] Merge WI-001094 to UAT

- force-app/main/default/flows/Opportunity_Error_when_Source_and_Source_Type_are_blank.flow-meta.xml
- force-app/main/default/flows/Source_Screen_Flow.flow-meta.xml
> [DevOps Center] Merge WI-001095 to Integration

- force-app/main/default/flows/Opportunity_Error_when_Source_and_Source_Type_are_blank.flow-meta.xml
- force-app/main/default/flows/Source_Screen_Flow.flow-meta.xml
> [DevOps Center] Merge WI-001095 to UAT

- force-app/main/default/objects/Account/fields/Latest_Stage_Of_Evolution__c.field-meta.xml
- force-app/main/default/objects/Account/fields/Latest_Valuation__c.field-meta.xml
- force-app/main/default/objects/Account/fields/Number_of_Fundraisings__c.field-meta.xml
- force-app/main/default/objects/Account/fields/Number_of_Grants__c.field-meta.xml
- force-app/main/default/objects/Account/fields/Primary_Date__c.field-meta.xml
- force-app/main/default/objects/Account/fields/Stage_After__c.field-meta.xml
- force-app/main/default/objects/Account/fields/Stage_Before__c.field-meta.xml
- force-app/main/default/objects/Account/fields/Stage_Of_Evolution_Transitions__c.field-meta.xml
- force-app/main/default/objects/Account/fields/Total_Amount_of_Fundraisings__c.field-meta.xml
- force-app/main/default/objects/Account/fields/Total_Amount_of_Grants__c.field-meta.xml
> [DevOps Center] Merge WI-001096 to Integration

- force-app/main/default/objects/AccountTeamMember/fields/Delete__c.field-meta.xml
> [DevOps Center] Merge WI-001083 to UAT

- force-app/main/default/objects/Client_Acceptance_Form__c/fields/Confirm_that_we_have_ascertained_the_tax__c.field-meta.xml
> [DevOps Center] Merge WI-001084 to UAT

- force-app/main/default/objects/Contact/fields/pse__Resource_Role__c.field-meta.xml
- force-app/main/default/objects/Contact/recordTypes/CRM_Contact.recordType-meta.xml
- force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
> [DevOps Center] Merge WI-001106 to Integration

- force-app/main/default/objects/Contact/fields/pse__Resource_Role__c.field-meta.xml
- force-app/main/default/objects/Contact/recordTypes/CRM_Contact.recordType-meta.xml
> [DevOps Center] Merge WI-001106 to UAT

- force-app/main/default/flexipages/Contact_Record_Page.flexipage-meta.xml
- force-app/main/default/flows/Survey_Adding_Campaign_Members.flow-meta.xml
- force-app/main/default/flows/Survey_Contact_Survey_Field_Month.flow-meta.xml
- force-app/main/default/objects/Contact/fields/Advocacy_Survey_Send_Month__c.field-meta.xml
- force-app/main/default/objects/Contact/fields/Field_Advocacy_Survey_Send_Month_Calc__c.field-meta.xml
> [DevOps Center] Merge WI-001107 to Integration

- force-app/main/default/flexipages/Contact_Record_Page.flexipage-meta.xml
- force-app/main/default/flows/Survey_Adding_Campaign_Members.flow-meta.xml
- force-app/main/default/flows/Survey_Contact_Survey_Field_Month.flow-meta.xml
- force-app/main/default/objects/Contact/fields/Advocacy_Survey_Send_Month__c.field-meta.xml
- force-app/main/default/objects/Contact/fields/Field_Advocacy_Survey_Send_Month_Calc__c.field-meta.xml
> [DevOps Center] Merge WI-001107 to UAT

- force-app/main/default/flows/CT_Release_Billing_Event.flow-meta.xml
> [DevOps Center] Merge WI-001109 to Integration

- force-app/main/default/flows/CT_Release_Billing_Event.flow-meta.xml
> [DevOps Center] Merge WI-001109 to UAT

- force-app/main/default/flows/CT_Release_Billing_Event.flow-meta.xml
> [DevOps Center] Merge WI-001110 to Integration

- force-app/main/default/flows/CT_Release_Billing_Event.flow-meta.xml
> [DevOps Center] Merge WI-001110 to UAT

- force-app/main/default/flexipages/projman_workspace3.flexipage-meta.xml
- force-app/main/default/flexipages/resource_manager_workspace3.flexipage-meta.xml
- force-app/main/default/objects/pse__Resource_Request__c/listViews/psaws__Held_and_Unheld_Resource_Requests.listView-meta.xml
- force-app/main/default/permissionsetgroups/Cooper_Parry_Business_Support_Team_Part_2.permissionsetgroup-meta.xml
> [DevOps Center] Merge WI-001113 to Integration

- force-app/main/default/flexipages/projman_workspace3.flexipage-meta.xml
- force-app/main/default/flexipages/resource_manager_workspace3.flexipage-meta.xml
- force-app/main/default/objects/pse__Resource_Request__c/listViews/psaws__Held_and_Unheld_Resource_Requests.listView-meta.xml
- force-app/main/default/permissionsetgroups/Cooper_Parry_Business_Support_Team_Part_2.permissionsetgroup-meta.xml
> [DevOps Center] Merge WI-001113 to UAT

- force-app/main/default/flows/Case_BTNC_Continuation_Form.flow-meta.xml
- force-app/main/default/objects/Continuation_Form__c/fields/Client_Names__c.field-meta.xml
> [DevOps Center] Merge WI-001116 to Integration

- force-app/main/default/flows/Case_BTNC_Continuation_Form.flow-meta.xml
- force-app/main/default/objects/Continuation_Form__c/fields/Client_Names__c.field-meta.xml
> [DevOps Center] Merge WI-001116 to UAT

- force-app/main/default/classes/BeauhurstAPIUtility.cls
- force-app/main/default/classes/UpdateAccountsFromBHBatch.cls
> [DevOps Center] Merge WI-001117 to Integration

- force-app/main/default/classes/BeauhurstAPIUtility.cls
- force-app/main/default/classes/UpdateAccountsFromBHBatch.cls
> [DevOps Center] Merge WI-001117 to UAT

- force-app/main/default/flows/Survey_update_should_be_sent_survey_checkbox.flow-meta.xml
> [DevOps Center] Merge WI-001118 to Integration

- force-app/main/default/classes/SmartSearchCompContTest.cls
> [DevOps Center] Merge WI-001119 to Integration

- force-app/main/default/classes/SmartSearchCompContTest.cls
> [DevOps Center] Merge WI-001119 to UAT

- force-app/main/default/classes/SmartSearchCompContTest.cls
> [DevOps Center] Merge WI-001124 to Integration

- force-app/main/default/classes/SmartSearchCompContTest.cls
> [DevOps Center] Merge WI-001124 to UAT

- force-app/main/default/flows/FFX_PSA_Project_Reactivation_from_Closure.flow-meta.xml
> [DevOps Center] Merge WI-001125 to Integration

- force-app/main/default/flexipages/Account_Record_Page.flexipage-meta.xml
> [DevOps Center] Merge WI-001126 to Integration

- force-app/main/default/flows/Survey_Trigger_Adding_of_Campaign_Members.flow-meta.xml
> [DevOps Center] Merge WI-001130 to Integration

- force-app/main/default/classes/SurveyInvitationTriggerHandler.cls
> [DevOps Center] Merge WI-001132 to Integration

- force-app/main/default/classes/SurveyInvitationTriggerHandler.cls
> [DevOps Center] Merge WI-001132 to UAT

- force-app/main/default/flows/Survey_Invitation_Scheduled_Flow_Send_Follow_up_Survey_Invitations.flow-meta.xml
> [DevOps Center] Merge WI-001133 to Integration

- force-app/main/default/flows/Survey_Invitation_Scheduled_Flow_Send_Follow_up_Survey_Invitations.flow-meta.xml
> [DevOps Center] Merge WI-001133 to UAT

- force-app/main/default/flexipages/Opportunity_Record_Page.flexipage-meta.xml
> [DevOps Center] Merge WI-001135 to Integration

- force-app/main/default/flexipages/Opportunity_Record_Page.flexipage-meta.xml
> [DevOps Center] Merge WI-001135 to UAT

- force-app/main/default/flows/Handle_Actual_Date_change_in_Milestone.flow-meta.xml
> [DevOps Center] Merge WI-001137 to Integration

- force-app/main/default/flows/Handle_Actual_Date_change_in_Milestone.flow-meta.xml
> [DevOps Center] Merge WI-001137 to UAT

- force-app/main/default/permissionsets/Account_Tags_Delete.permissionset-meta.xml
> [DevOps Center] Merge WI-001122 to Integration

- force-app/main/default/permissionsets/Account_Tags_Delete.permissionset-meta.xml
> [DevOps Center] Merge WI-001122 to UAT

- force-app/main/default/flows/Survey_NPS_Score_6_or_Less.flow-meta.xml
> [DevOps Center] Merge WI-001138 to UAT

- force-app/main/default/flows/Survey_NPS_Score_6_or_Less.flow-meta.xml
DevOps Center created this change request for DevOps Center use only. Due to the potential for data corruption, DO NOT MERGE this change request.
> [DO NOT MERGE] For DevOps Center use only - UAT to Production

- force-app/main/default/flows/Survey_NPS_Score_6_or_Less.flow-meta.xml
> [DevOps Center] Merge WI-001138 to Production

- force-app/main/default/flexipages/Opportunity_Record_Page.flexipage-meta.xml
- force-app/main/default/flows/FFX_PSA_Project.flow-meta.xml
> [DevOps Center] Merge WI-001143 to Integration

- force-app/main/default/flexipages/Opportunity_Record_Page.flexipage-meta.xml
- force-app/main/default/flows/FFX_PSA_Project.flow-meta.xml
> [DevOps Center] Merge WI-001143 to UAT

- force-app/main/default/flows/Opportunity_Audit_Estimate_Validation.flow-meta.xml
> [DevOps Center] Merge WI-001146 to UAT

- force-app/main/default/flexipages/Opportunity_Record_Page.flexipage-meta.xml
> [DevOps Center] Merge WI-001147 to UAT

- force-app/main/default/flexipages/Opportunity_Record_Page.flexipage-meta.xml
> [DevOps Center] Merge WI-001147 to Production

- force-app/main/default/flows/FFX_PSA_Project.flow-meta.xml
> [DevOps Center] Merge WI-001148 to UAT

- force-app/main/default/permissionsets/Reports_Permission_Set.permissionset-meta.xml
> [DevOps Center] Merge WI-001150 to UAT

- force-app/main/default/permissionsets/Cooper_Parry_Managers_PS.permissionset-meta.xml
- force-app/main/default/permissionsets/Cooper_Parry_Managers_PS2.permissionset-meta.xml
> [DevOps Center] Merge WI-001151 to UAT

- force-app/main/default/flows/Opportunity_Update_Naming_Convention.flow-meta.xml
> [DevOps Center] Merge WI-001152 to UAT

- force-app/main/default/flows/Opportunity_Update_Naming_Convention.flow-meta.xml
> [DevOps Center] Merge WI-001152 to Production

- force-app/main/default/layouts/pse__Proj__c-CT_PSA_Delivery_Project_Layout.layout-meta.xml
- force-app/main/default/layouts/pse__Proj__c-FFX PSA PSR Project Layout.layout-meta.xml
- force-app/main/default/layouts/pse__Proj__c-FFX PSA Project Detail Layout.layout-meta.xml
- force-app/main/default/layouts/pse__Proj__c-PSA Project Detail Layout.layout-meta.xml
- force-app/main/default/layouts/pse__Proj__c-pse__Project Detail Layout.layout-meta.xml
- force-app/main/default/layouts/pse__Proj__c-pse__Project Layout.layout-meta.xml
- force-app/main/default/objects/pse__Proj__c/webLinks/New.webLink-meta.xml
> [DevOps Center] Merge WI-001144 to Production

- force-app/main/default/permissionsets/Cooper_Parry_Business_Support_Team_PS.permissionset-meta.xml
- force-app/main/default/permissionsets/Cooper_Parry_Business_Support_Team_PS2.permissionset-meta.xml
> [DevOps Center] Merge WI-001154 to UAT

- force-app/main/default/permissionsets/Cooper_Parry_Business_Support_Team_PS.permissionset-meta.xml
> [DevOps Center] Merge WI-001156 to UAT

- force-app/main/default/flows/Opportunity_Audit_Estimate_Validation.flow-meta.xml
> [DevOps Center] Merge WI-001146 to Production

- force-app/main/default/classes/SurveyInvitationTriggerHandler.cls
> [DevOps Center] Merge WI-001159 to UAT

- force-app/main/default/classes/SurveyInvitationTriggerHandler.cls
> [DevOps Center] Merge WI-001159 to Production

- force-app/main/default/layouts/pse__Proj__c-FFX PSA Project Detail Layout.layout-meta.xml
> [DevOps Center] Merge WI-001160 to UAT

- force-app/main/default/flows/Case_BTNC_Continuation_Form.flow-meta.xml
> [DevOps Center] Merge WI-001162 to UAT

- force-app/main/default/flows/Case_BTNC_Continuation_Form.flow-meta.xml
> [DevOps Center] Merge WI-001163 to UAT

- force-app/main/default/flows/Account_Account_Name_Change_Error.flow-meta.xml
> [DevOps Center] Merge WI-001165 to UAT

- force-app/main/default/flows/Project_Closed_for_Time_Entry_Field_Validation.flow-meta.xml
> [DevOps Center] Merge WI-001167 to UAT

- force-app/main/default/flows/Account_Account_Name_Change_Error.flow-meta.xml
- force-app/main/default/objects/Account/validationRules/V1_Restrict_Account_Name_Edit.validationRule-meta.xml
> [DevOps Center] Merge WI-001171 to UAT

- force-app/main/default/flows/Cash_Entry_Record_Triggered_Flow.flow-meta.xml
- force-app/main/default/flows/Credit_Note_Record_Triggered_Flow.flow-meta.xml
> [DevOps Center] Merge WI-001173 to UAT

- force-app/main/default/permissionsets/Reports_Permission_Set.permissionset-meta.xml
> [DevOps Center] Merge WI-001166 to Production

- force-app/main/default/flows/Account_Account_Name_Change_Error.flow-meta.xml
- force-app/main/default/objects/Account/validationRules/V1_Restrict_Account_Name_Edit.validationRule-meta.xml
> [DevOps Center] Merge WI-001171 to Production

- force-app/main/default/flexipages/Resource_Request_Lightning_Page1.flexipage-meta.xml
> [DevOps Center] Merge WI-001174 to UAT

- force-app/main/default/flexipages/Case_Record_Page.flexipage-meta.xml
> [DevOps Center] Merge WI-001176 to UAT

- force-app/main/default/permissionsets/Cooper_Parry_Managers_PS.permissionset-meta.xml
- force-app/main/default/permissionsets/Cooper_Parry_Managers_PS2.permissionset-meta.xml
> [DevOps Center] Merge WI-001178 to UAT

- force-app/main/default/flexipages/Account_Record_Page_Three_Column.flexipage-meta.xml
> [DevOps Center] Merge WI-001180 to UAT

- force-app/main/default/flexipages/Account_Record_Page_Three_Column.flexipage-meta.xml
> [DevOps Center] Merge WI-001180 to Production

- force-app/main/default/classes/SurveyInvitationTriggerHandler.cls
- force-app/main/default/triggers/SurveyInvitationTrigger.trigger
> [DevOps Center] Merge WI-001181 to UAT

- force-app/main/default/objects/Account/fields/attachCustomerStatementPdf__c.field-meta.xml
> [DevOps Center] Merge WI-001182 to UAT

- force-app/main/default/flows/CT_Set_Default_ProjectName.flow-meta.xml
- force-app/main/default/flows/FFX_PSA_Project.flow-meta.xml
> [DevOps Center] Merge WI-001185 to UAT

- force-app/main/default/flows/CT_Set_Default_ProjectName.flow-meta.xml
- force-app/main/default/flows/FFX_PSA_Project.flow-meta.xml
> [DevOps Center] Merge WI-001185 to Production

- force-app/main/default/objects/c2g__CollectionsPlusSettings__c/c2g__CollectionsPlusSettings__c.object-meta.xml
- force-app/main/default/objects/c2g__CollectionsPlusSettings__c/fields/c2g__CustomerStatementCongaAttachmentPrefix__c.field-meta.xml
> [DevOps Center] Merge WI-001183 to UAT

- force-app/main/default/layouts/pse__Resource_Request__c-FFX PSA Resource Request Layout.layout-meta.xml
- force-app/main/default/objects/pse__Resource_Request__c/validationRules/Milestone_is_Required.validationRule-meta.xml
> [DevOps Center] Merge WI-001188 to UAT

- force-app/main/default/flexipages/CP_Note_Record_Page.flexipage-meta.xml
> [DevOps Center] Merge WI-001187 to UAT

- force-app/main/default/permissionsets/Cooper_Parry_Finance_PS.permissionset-meta.xml
- force-app/main/default/permissionsets/Cooper_Parry_Finance_PS2.permissionset-meta.xml
> [DevOps Center] Merge WI-001189 to UAT

- force-app/main/default/objects/pse__Proj__c/validationRules/Lowest_level_practice_Allowed.validationRule-meta.xml
> [DevOps Center] Merge WI-001177 to Production

- force-app/main/default/objects/Reprocess_Event__e/Reprocess_Event__e.object-meta.xml
- force-app/main/default/objects/Reprocess_Event__e/fields/Error_Log_ID__c.field-meta.xml
- force-app/main/default/objects/Reprocess_Event__e/fields/Event_Type__c.field-meta.xml
- force-app/main/default/objects/Reprocess_Event__e/fields/Original_Payload__c.field-meta.xml
- force-app/main/default/objects/Reprocess_Event__e/fields/Unique_ID__c.field-meta.xml
- force-app/main/default/objects/Reprocess_Salesforce_Event__e/Reprocess_Salesforce_Event__e.object-meta.xml
- force-app/main/default/objects/Reprocess_Salesforce_Event__e/fields/Error_Log_ID__c.field-meta.xml
- force-app/main/default/objects/Reprocess_Salesforce_Event__e/fields/Event_Type__c.field-meta.xml
- force-app/main/default/objects/Reprocess_Salesforce_Event__e/fields/Original_Payload__c.field-meta.xml
- force-app/main/default/objects/Reprocess_Salesforce_Event__e/fields/Unique_ID__c.field-meta.xml
> [DevOps Center] Merge WI-001190 to UAT

- force-app/main/default/classes/SurveyInvitationTriggerHandler.cls
- force-app/main/default/triggers/SurveyInvitationTrigger.trigger
> [DevOps Center] Merge WI-001181 to Production

- force-app/main/default/flows/CT_Set_Default_ProjectName.flow-meta.xml
- force-app/main/default/flows/FFX_PSA_Project.flow-meta.xml
> [DevOps Center] Merge WI-001191 to UAT

- force-app/main/default/layouts/Error_Logs__c-Error Log Layout.layout-meta.xml
- force-app/main/default/objects/Error_Logs__c/fields/Error_Log_ID__c.field-meta.xml
- force-app/main/default/objects/Error_Logs__c/fields/Event_Type__c.field-meta.xml
- force-app/main/default/objects/Error_Logs__c/fields/Original_Payload__c.field-meta.xml
- force-app/main/default/objects/Error_Logs__c/fields/Source_System__c.field-meta.xml
- force-app/main/default/objects/Error_Logs__c/fields/Status__c.field-meta.xml
- force-app/main/default/objects/Error_Logs__c/fields/Timestamp__c.field-meta.xml
- force-app/main/default/objects/Error_Logs__c/fields/Transformed_Payload__c.field-meta.xml
- force-app/main/default/objects/Error_Logs__c/fields/Unique_ID__c.field-meta.xml
> [DevOps Center] Merge WI-001193 to UAT

- force-app/main/default/flexipages/Case_Record_Page.flexipage-meta.xml
> [DevOps Center] Merge WI-001194 to UAT

- force-app/main/default/flows/Case_BTNC_Continuation_Form.flow-meta.xml
> [DevOps Center] Merge WI-001163 to Production

- force-app/main/default/layouts/pse__Proj__c-FFX PSA Project Detail Layout.layout-meta.xml
> [DevOps Center] Merge WI-001160 to Production

- force-app/main/default/flows/Opportunity_Send_Custom_Notification.flow-meta.xml
> [DevOps Center] Merge WI-001199 to UAT

- force-app/main/default/flows/Opportunity_Send_Custom_Notification.flow-meta.xml
> [DevOps Center] Merge WI-001199 to Production

- force-app/main/default/flows/Error_Logs_Screenflow_Trigger_Platform_Event.flow-meta.xml
- force-app/main/default/objects/Reprocess_Event__e/fields/SF_Record_ID__c.field-meta.xml
- force-app/main/default/objects/Reprocess_Salesforce_Event__e/fields/SF_Record_ID__c.field-meta.xml
> [DevOps Center] Merge WI-001201 to UAT

- force-app/main/default/flexipages/Account_Record_Page_Three_Column.flexipage-meta.xml
> [DevOps Center] Merge WI-001204 to UAT

- force-app/main/default/classes/BatchAddSharingToPartner.cls
- force-app/main/default/classes/BatchAddSharingToPartner.cls-meta.xml
- force-app/main/default/classes/BatchAddSharingToPartnerTest.cls
- force-app/main/default/classes/BatchAddSharingToPartnerTest.cls-meta.xml
- force-app/main/default/classes/ProjectTriggerHandler.cls
- force-app/main/default/classes/ProjectTriggerHandler.cls-meta.xml
- force-app/main/default/classes/ProjectTriggerHandlerTest.cls
- force-app/main/default/classes/ProjectTriggerHandlerTest.cls-meta.xml
- force-app/main/default/triggers/ProjectTrigger.trigger
- force-app/main/default/triggers/ProjectTrigger.trigger-meta.xml
> [DevOps Center] Merge WI-001206 to UAT

- force-app/main/default/objects/Lead/fields/Lead_Recipient__c.field-meta.xml
> [DevOps Center] Merge WI-001208 to UAT

- force-app/main/default/classes/BatchAddSharingToPartner.cls
- force-app/main/default/classes/BatchAddSharingToPartnerTest.cls
- force-app/main/default/classes/ProjectTriggerHandler.cls
- force-app/main/default/classes/ProjectTriggerHandlerTest.cls
- force-app/main/default/triggers/ProjectTrigger.trigger
> [DevOps Center] Merge WI-001209 to UAT

- force-app/main/default/groups/Cooper_Parry_Managers.group-meta.xml
> [DevOps Center] Merge WI-001210 to UAT

- force-app/main/default/groups/Cooper_Parry_Managers.group-meta.xml
> [DevOps Center] Merge WI-001210 to Production

- force-app/main/default/notificationtypes/Lead_Pickup_Notification.notiftype-meta.xml
> [DevOps Center] Merge WI-001211 to UAT

- force-app/main/default/classes/BatchAddSharingToPartner.cls
- force-app/main/default/classes/BatchAddSharingToPartner.cls-meta.xml
- force-app/main/default/classes/BatchAddSharingToPartnerTest.cls
- force-app/main/default/classes/BatchAddSharingToPartnerTest.cls-meta.xml
- force-app/main/default/classes/ProjectTriggerHandler.cls
- force-app/main/default/classes/ProjectTriggerHandler.cls-meta.xml
- force-app/main/default/classes/ProjectTriggerHandlerTest.cls
- force-app/main/default/classes/ProjectTriggerHandlerTest.cls-meta.xml
- force-app/main/default/triggers/ProjectTrigger.trigger
- force-app/main/default/triggers/ProjectTrigger.trigger-meta.xml
> [DevOps Center] Merge WI-001209 to Production

- force-app/main/default/notificationtypes/Lead_Pickup_Notification.notiftype-meta.xml
> [DevOps Center] Merge WI-001211 to Production

- force-app/main/default/flexipages/Account_Record_Page_Three_Column.flexipage-meta.xml
> [DevOps Center] Merge WI-001204 to Production

- force-app/main/default/classes/CSVRecordUploaderBatch.cls
- force-app/main/default/classes/CSVRecordUploaderBatchTest.cls
- force-app/main/default/classes/CSVRecordUploaderController.cls
- force-app/main/default/classes/CSVRecordUploaderControllerTest.cls
- force-app/main/default/lwc/cSVRecordUploader/cSVRecordUploader.html
- force-app/main/default/lwc/cSVRecordUploader/cSVRecordUploader.js
> [DevOps Center] Merge WI-001217 to UAT

- force-app/main/default/flexipages/Contact_Record_Page.flexipage-meta.xml
- force-app/main/default/flexipages/Contact_Record_Page_Three_Column.flexipage-meta.xml
- force-app/main/default/objects/Contact/fields/Acquisition_Marker__c.field-meta.xml
- force-app/main/default/objects/Contact/recordTypes/CRM_Contact.recordType-meta.xml
- force-app/main/default/objects/Contact/recordTypes/PSA_Resource.recordType-meta.xml
> [DevOps Center] Merge WI-001219 to UAT

- force-app/main/default/flexipages/Contact_Record_Page.flexipage-meta.xml
- force-app/main/default/flexipages/Contact_Record_Page_Three_Column.flexipage-meta.xml
- force-app/main/default/objects/Contact/fields/Acquisition_Marker__c.field-meta.xml
- force-app/main/default/objects/Contact/recordTypes/CRM_Contact.recordType-meta.xml
- force-app/main/default/objects/Contact/recordTypes/PSA_Resource.recordType-meta.xml
> [DevOps Center] Merge WI-001219 to Production

- force-app/main/default/classes/CSVRecordUploaderBatch.cls
- force-app/main/default/classes/CSVRecordUploaderBatchTest.cls
- force-app/main/default/classes/CSVRecordUploaderController.cls
- force-app/main/default/classes/CSVRecordUploaderControllerTest.cls
- force-app/main/default/lwc/cSVRecordUploader/cSVRecordUploader.html
> [DevOps Center] Merge WI-001221 to UAT

- force-app/main/default/flows/Case_Naming_Convention.flow-meta.xml
> [DevOps Center] Merge WI-001223 to UAT

- force-app/main/default/permissionsets/Expense_Admin_Edit.permissionset-meta.xml
> [DevOps Center] Merge WI-001224 to UAT

- force-app/main/default/classes/SharepointCompCont.cls
- force-app/main/default/lwc/sharepointComp/sharepointComp.css
- force-app/main/default/lwc/sharepointComp/sharepointComp.html
> [DevOps Center] Merge WI-001226 to UAT

- force-app/main/default/classes/SharepointCompCont.cls
- force-app/main/default/lwc/sharepointComp/sharepointComp.css
- force-app/main/default/lwc/sharepointComp/sharepointComp.html
> [DevOps Center] Merge WI-001226 to Production

- force-app/main/default/flows/CT_Release_Billing_Event.flow-meta.xml
> [DevOps Center] Merge WI-001231 to UAT

- force-app/main/default/flows/CT_Release_Billing_Event.flow-meta.xml
> [DevOps Center] Merge WI-001231 to Production

- force-app/main/default/globalValueSets/Assignment_Type.globalValueSet-meta.xml
- force-app/main/default/objects/Opportunity/fields/Assignment_Type__c.field-meta.xml
> [DevOps Center] Merge WI-001232 to UAT

- force-app/main/default/objects/Opportunity/validationRules/V4_Loss_Reason_Required_On_Closed_Lost.validationRule-meta.xml
> [DevOps Center] Merge WI-001234 to UAT

- force-app/main/default/globalValueSets/Assignment_Type.globalValueSet-meta.xml
- force-app/main/default/objects/Opportunity/fields/Assignment_Type__c.field-meta.xml
> [DevOps Center] Merge WI-001232 to Production

- force-app/main/default/objects/pse__Proj__c/fields/CT_Recognisable_Value__c.field-meta.xml
> [DevOps Center] Merge WI-001238 to UAT

- force-app/main/default/objects/pse__Proj__c/fields/CT_Recognisable_Value__c.field-meta.xml
> [DevOps Center] Merge WI-001238 to Production

- force-app/main/default/permissionsets/Estimate_Role_Request_Access.permissionset-meta.xml
> [DevOps Center] Merge WI-001230 to Production

- force-app/main/default/layouts/Error_Logs__c-Error Log Layout.layout-meta.xml
- force-app/main/default/objects/Error_Logs__c/fields/Error_Log_ID__c.field-meta.xml
- force-app/main/default/objects/Error_Logs__c/fields/Event_Type__c.field-meta.xml
- force-app/main/default/objects/Error_Logs__c/fields/Original_Payload__c.field-meta.xml
- force-app/main/default/objects/Error_Logs__c/fields/Source_System__c.field-meta.xml
- force-app/main/default/objects/Error_Logs__c/fields/Status__c.field-meta.xml
- force-app/main/default/objects/Error_Logs__c/fields/Timestamp__c.field-meta.xml
- force-app/main/default/objects/Error_Logs__c/fields/Transformed_Payload__c.field-meta.xml
- force-app/main/default/objects/Error_Logs__c/fields/Unique_ID__c.field-meta.xml
> [DevOps Center] Merge WI-001193 to Production
